---
- hosts: localhost
  connection: local
  roles:
    - role: "{{ role_name }}"
  
- name: download_data_playbook
  hosts: localhost
  connection: local
  tasks: 
  - name: Create downloader directory 
    ansible.builtin.file:
      path: /downloader/repo
      state: directory
      mode: '0775'
    
  - name: Clone downloader repository
    git:
      repo: https://github.com/AkumuYuma/eodag-data-downloader.git
      dest: /downloader/repo
      clone: yes
      update: yes
  
  - name: Install and init miniconda
    ansible.builtin.shell: 
      cmd: "bash {{ conda_downloader }}"
  
  - name: Install virtualenv via pip
    ansible.builtin.pip: 
      name: virtualenv
  
  - name: Create Virtualenv for downloader 
    ansible.builitin.shell: 
  
  # - name: Install requirements for data download
  #   ansible.builtin.pip:
  #     requirements: /downloader/requirements.txt
      # virtualenv: /downloader/venv
      # virtualenv_python: python3.10.9
  - name: Install requirements for data download
    ansible.builtin.pip:
      name: eodag 

  - name: Install requirements for data download
    ansible.builtin.pip:
      name: ruamel.yaml 

  # - name: Printing variable valus
  #   ansible.builtin.debug:
  #     msg: 
  #     - "Variabile: '{{ downloading_input[0] }}'"
  
  # - name: Download data
  #   ansible.builtin.script: /downloader/downloader.py "{{ downloading_input[0] }}"
  #   args:
  #     executable: python3
  - name: Download data
    ansible.builtin.command: python3 /downloader/downloader.py "{{ downloading_input[0] }}"

  - name: Moving image files from downloading folder to the final path 
    ansible.builtin.shell:
      cmd: mv "/downloader/{{ downloading_input[0]["saving_settings"]["base_path"] }}" /jupyter-mounts/shared/
      chdir: /

  
      